spring:
  application:
    name: wallet-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wallet}
    username: ${SPRING_DATASOURCE_USERNAME:wallet}
    password: ${SPRING_DATASOURCE_PASSWORD:wallet}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8080
