spring:
  application:
    name: wallet-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: wallet
    password: wallet

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080